#!/bin/sh
#
# Run KNoT-control
#

node /usr/local/bin/knot-control-source/server.js &
echo $! > /tmp/knot-control.pid

PIDFILE=/tmp/knot-control.pid
PID=`cat $PIDFILE`

while [ -e /proc/$PID ]
do
	#Wait
	sleep 1
done
